### ISSUE TITLE
Banner: Image doesn't occupy the entire width of the banner section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hevi-Haul#113]
![image](https://cloud.githubusercontent.com/assets/11186313/13839034/2f1a9e78-ec53-11e5-9507-22830a5581ab.png)

**Comment by Rahul-titan** [comment]
![homepage screenshot](https://cloud.githubusercontent.com/assets/13828548/13867761/642dd9b4-ece8-11e5-9c7a-867b3bd22fd4.png)

**Comment by Rahul-titan** [comment]
![homepage screenshot](https://cloud.githubusercontent.com/assets/13828548/13867810/cfe19394-ece8-11e5-8a5b-aae9a7d6debd.png)
