### ISSUE TITLE
News - post title was displayed cut. As per titan standard, post title should support at least 2 liner post title display

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Hevi-Haul#79]
![image](https://cloud.githubusercontent.com/assets/12791909/13383580/b8225b38-dec6-11e5-8905-4c43ae4c1225.png)

**Comment by dremensayson** [comment]
Above issue is already fixed but don't limit at least 2 lines, it should display all title regardless the length of it.

**Comment by roseliesromeo** [comment]
QA Lead: Please revert to one line only as per scope.
