### ISSUE TITLE
Inner Banner was displayed stretch

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Hevi-Haul#91]
![image](https://cloud.githubusercontent.com/assets/12791909/13384995/8200e62c-ded6-11e5-9afb-02fc16389d84.png)

**Comment by Rahul-titan** [comment]
Please upload banner images with minimum width 1920px, if not, 
Causes:  Banner image will be displayed in its own with. or it will be stretched to the width of its container.

**Comment by dremensayson** [comment]
banner image still stretch
