### ISSUE TITLE
Homepage:Header - align the email address to the Contact menu

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Hevi-Haul#92]
![image](https://cloud.githubusercontent.com/assets/17717843/13593799/98fbadc6-e539-11e5-9161-4c2b8ca8cf8e.png)

**Comment by Rahul-titan** [comment]
![contactalignment](https://cloud.githubusercontent.com/assets/13828548/13701090/5db31ad2-e7ab-11e5-800c-c0b65b188bf9.jpg)
Its aligned. pls hover or active it.

**Comment by roseliesromeo** [comment]
Design error.
