### ISSUE TITLE
News Single Page:Banner - limit 2 lines to make it consistent in the News Listing page

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Hevi-Haul#94]
![image](https://cloud.githubusercontent.com/assets/17717843/13595078/9eae7df2-e543-11e5-819d-740bf8e736d1.png)

**Comment by roseliesromeo** [comment]
It is still not limited to 2 lines.  
![image](https://cloud.githubusercontent.com/assets/11186313/13839657/b4f57168-ec57-11e5-8769-71e1d590258c.png)

**Comment by roseliesromeo** [comment]
Breadcrumbs isn't displayed for post with two lines
